### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by mayankdwivedi11** [MidhunBalan/Setmore_IssueRepository#7]

**Comment by MidhunBalan** [comment]
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/539724/conversations/13116495084

Events are not showing on the Setmore calendar.

**Comment by PandiSundaram** [comment]
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/539724/conversations/13116495084
The issue got fixed. You can reply back to the customer

**Comment by PandiSundaram** [comment]
Issue fixed
